### PR TITLE
VSCode scripts to enable other IDE for development

### PR DESCRIPTION
**Pull request by KaueReinbold**
- Create base tasks for manage de application and run Samples.
- Provide the ability to debug the sample also.

### CODE REVIEW

**Comment by KaueReinbold** [comment]
This PR must be approved after the #9, there are some build check configure

**Comment by EdneySilva** [comment]
Hi @KaueReinbold, I've read about the **checker error** and found this on the [https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli#publish-errors](official documentation), and conclude that to solve we need to change the version from this package to avoid this conflict.

It also make a sense once we are fixing a bug, so we need to change the last version number 1.0.4.**2**, so please inscrise the version from this package to allow us to procceed with this pull request.

**Comment by KaueReinbold** [comment]
Got it, I will update the PR.

Are you using the [semver](https://semver.org/) approach to manage the version?

**Comment by EdneySilva** [comment]
@KaueReinbold, yes Kaue, I'm

**Comment by KaueReinbold** [comment]
@EdneySilva Done

**Pull request merged**
